### ISSUE TITLE
Further contact about this app

### ISSUE THREAD

**Issue by LATL9** [16magrzywacz/Unscramble#1]
**(There was no public email address for your user, so I am opening an issue instead. Feel free to close afterwards.)**

I am currently in the process of developing an application involving the "scanning" of a Rubik's Cube with a camera.
In this search, I have recently discovered your application, which does an excellent job at implementing this function.
As part of the research that I am conducting, **I wish to get in contact with you** on how (and why) you created it (a brief explanation will do), as yours seems to have the best implementation I can find, with the hope of improving the development of mine too.
Many thanks.

**Comment by 16magrzywacz** [comment]
Hi, perhaps take a look at [this file](https://github.com/16magrzywacz/Unscramble/blob/master/app/src/main/java/com/matthew/unscramble/CameraInputActivity.java#L183-L253). The logic for parsing camera input is within the highlighted function 😃

**Comment by LATL9** [comment]
Thanks! Sorry for the late reply.
Just to clarify, am I allowed to cite you in the research project I am conducting? I want to portray different methods of implementing a Rubik's Cube solver by showing off existing implementations.

**Comment by 16magrzywacz** [comment]
Of course, that's not a problem. I created this application as part of a project for college, and so I thought an app like this would have enough complexity to it and motivate me to work on it. I also noticed a lot of the apps on the market had a similar implementation, but followed a fewest moves algorithm to solve the cube, instead of a beginner friendly method, hence I came up with the idea.

**Comment by LATL9** [comment]
Oh, I see. Cheers!
